### PR TITLE
Add plugins.qmltypes. JB#59899

### PR DESCRIPTION
**Pull request by martyone**

### CODE REVIEW

**Comment by pvuorela** [comment]
The battery and other providers should be here an implementation detail which shouldn't be leaking outside. The public API is ContextProperty.qml and based on its "key" property it internally loads some provider to output the "value" property.

Being just that, do we need any qmltypes here?

**Comment by martyone** [comment]
The effort has been to provide coding assistance for all APIs, with no distinction between internal and public APIs. Platform developers are not 2nd class citizen :)

**Comment by pvuorela** [comment]
> The effort has been to provide coding assistance for all APIs, with no distinction between internal and public APIs. Platform developers are not 2nd class citizen :)

Not sure if talking about the same thing. The provider thing is only internal to the module so would be helpful if somebody developed providers inside this repository. New providers I will not accept here, this is here mostly for backwards compatibility.

**Comment by martyone** [comment]
Yes, understood, only helpful to someone working on src/providers/Battery.qml. Even that you find it utterly useless, the fact that I do not make an exception actually saves me a maintenance effort.

**Comment by pvuorela** [comment]
Ok. I'll approve. Shouldn't hurt too much even if it didn't provide much.

**Review by pvuorela — APPROVED** [review]

**Pull request merged**
